services:
  blog-db:
    image: postgres:18-alpine
    container_name: blog-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432"

  mongodb:
    image: 'mongo:8.0.0'
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME=root'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_DATABASE=blog'
    ports:
      - '27017'

  spring-boot-demo:
    image: sivaprasadreddy/spring-boot-demo
    container_name: spring-boot-demo
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_DATASOURCE_URL: jdbc:postgresql://blog-db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: unless-stopped
    profiles:
      - app