spring.application.name=spring-boot-demo
server.port=8080
spring.docker.compose.lifecycle-management=start_and_stop

#### App ####
blog.support-email=siva@gmail.com
blog.posts-page-size=20
blog.token-expires-in-minutes=30
blog.token-secret=secretsecretsecret12345678901234567890

#### Spring Modulith ####
spring.modulith.events.jdbc.schema-initialization.enabled=true
spring.modulith.events.republish-outstanding-events-on-restart=true

#### Actuator ####
management.endpoints.web.exposure.include=info,health,metrics
management.endpoint.health.probes.enabled=true

#### Logging ####
logging.level.root=INFO
logging.level.com.sivalabs=DEBUG
logging.include-application-name=false
#logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
#logging.level.org.springframework.security=DEBUG

#### Database ####
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
#spring.jpa.properties.hibernate.format_sql=true

#### Springdoc ####
springdoc.paths-to-match=/api/**