spring.application.name=spring-boot-demo
server.port=8080
spring.docker.compose.lifecycle-management=start_only
spring.mvc.hiddenmethod.filter.enabled=true

######## Spring Modulith Configuration  #########
spring.modulith.events.jdbc.schema-initialization.enabled=true
spring.modulith.events.republish-outstanding-events-on-restart=true

######## Actuator Configuration  #########
management.endpoints.web.exposure.include=info,health,metrics
management.endpoint.health.probes.enabled=true
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.tags.application=${spring.application.name}
management.observations.key-values.application=${spring.application.name}
management.tracing.enabled=false
management.tracing.sampling.probability=1.0

################### Logging Configuration ##########################
logging.level.root=INFO
logging.level.com.sivalabs=DEBUG
logging.include-application-name=false
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
#logging.level.org.springframework.security=DEBUG

################### DB Configuration ##########################
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
#spring.jpa.properties.hibernate.format_sql=true

######## MongoDB Configuration  #########
spring.data.mongodb.host=localhost
spring.data.mongodb.port=12707
spring.data.mongodb.database=blog
spring.data.mongodb.username=root
spring.data.mongodb.password=secret
spring.data.mongodb.authentication-database=admin

################### App Configuration ##########################
blog.support-email=siva@gmail.com
blog.posts-per-page=5
blog.newsletter-job-cron=0 0 9 * * 6
blog.cors.path-pattern=/api/**
blog.cors.allowed-origins=*
blog.cors.allowed-methods=*
blog.cors.allowed-headers=*

blog.openapi.title=Blog API
blog.openapi.description=Blog API Swagger Documentation
blog.openapi.version=v1.0.0
blog.openapi.contact.name=SivaLabs
blog.openapi.contact.email=support@sivalabs.in

blog.jwt.issuer=SivaLabs
blog.jwt.expires-in-seconds=604800
blog.jwt.private-key=classpath:certs/private.pem
blog.jwt.public-key=classpath:certs/public.pem

springdoc.paths-to-match=/api/**