INSERT INTO users(id, email, password, name, role) VALUES
(1,'admin@gmail.com','$2a$10$I/ijZUPJEmNWmDP5GkcwaeoYkyMNW.GuqPwOMAwOWqNwiBFmhTaBK','Administrator', 'ROLE_ADMIN'),
(2,'siva@gmail.com','$2a$10$I/ijZUPJEmNWmDP5GkcwaeoYkyMNW.GuqPwOMAwOWqNwiBFmhTaBK','Siva Prasad', 'ROLE_USER');

INSERT INTO POSTS(id, title, slug, content, created_by, created_at) VALUES
(1,'Getting Started with Spring AI: Building LLM-Powered Applications','getting-started-with-spring-ai','Spring AI brings the power of large language models to the Spring ecosystem. In this post we explore how to integrate OpenAI and Ollama into a Spring Boot application using the Spring AI abstraction layer, including prompt templates, chat memory, and structured output parsing.', 1, '2026-06-20'),
(2,'Deploying Spring Boot Apps on Kubernetes with Helm','deploying-spring-boot-on-kubernetes-with-helm','Kubernetes has become the de facto standard for container orchestration. In this guide we walk through packaging a Spring Boot application as a Docker image, writing Helm charts, configuring liveness and readiness probes, and setting up horizontal pod autoscaling on a managed Kubernetes cluster.', 2, '2026-06-15'),
(3,'Building Agentic AI Workflows with Spring AI and Model Context Protocol','agentic-ai-workflows-spring-ai-mcp','The Model Context Protocol (MCP) enables AI agents to interact with external tools and data sources in a standardized way. This post shows how to build a multi-step AI agent in Spring Boot that uses MCP servers to query databases, call REST APIs, and reason over the results.', 2, '2026-06-10'),
(4,'Event-Driven Microservices with Spring Boot and Apache Kafka','event-driven-microservices-spring-boot-kafka','Event-driven architecture decouples services and improves resilience at scale. We demonstrate how to design event-driven microservices using Spring Boot, Spring Kafka, and the outbox pattern to guarantee at-least-once delivery without distributed transactions.', 2, '2026-05-28'),
(5,'Infrastructure as Code with Terraform and AWS: A Practical Guide','infrastructure-as-code-terraform-aws','Managing cloud infrastructure manually is error-prone and hard to reproduce. This post covers using Terraform to provision an AWS environment — VPC, ECS Fargate, RDS Aurora, and an Application Load Balancer — with remote state stored in S3 and state locking via DynamoDB.', 2, '2026-05-15'),
(6,'Observability in Spring Boot: Metrics, Traces, and Logs with OpenTelemetry','observability-spring-boot-opentelemetry','Modern cloud-native applications require deep observability. We look at how to instrument a Spring Boot 3 application with Micrometer Tracing and the OpenTelemetry SDK, export data to Grafana Tempo and Loki, and build dashboards that correlate traces, metrics, and logs.', 2, '2026-04-30'),
(7,'Vector Databases and Retrieval-Augmented Generation with Spring AI','vector-databases-rag-spring-ai','Retrieval-Augmented Generation (RAG) grounds LLM responses in your own data. This article explains how to ingest documents, generate embeddings, store them in pgvector or Weaviate, and wire everything together with Spring AI to build a context-aware Q&A chatbot.', 2, '2026-04-10'),
(8,'Securing Cloud-Native APIs with OAuth2, JWT, and Spring Security','securing-cloud-native-apis-oauth2-jwt-spring-security','Zero-trust security starts at the API layer. We cover how to configure Spring Security 6 with Keycloak as an authorization server, validate JWTs with JWKS rotation, enforce fine-grained RBAC using method-level security, and protect reactive endpoints in Spring WebFlux.', 2, '2026-03-22'),
(9,'GitOps with ArgoCD: Continuous Delivery for Kubernetes Workloads','gitops-argocd-continuous-delivery-kubernetes','GitOps treats Git as the single source of truth for declarative infrastructure and application state. This post walks through setting up ArgoCD, structuring a multi-environment Helm repository, configuring ApplicationSets, and automating progressive delivery with Argo Rollouts.', 2, '2026-03-05')
;